---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    pam: "#{source_dir}"
