---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat: https://github.com/simp/puppetlabs-concat
    haveged: https://github.com/simp/pupmod-simp-haveged
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    simplib: https://github.com/simp/pupmod-simp-simplib
    ssh: https://github.com/simp/pupmod-simp-ssh
    sssd: https://github.com/simp/pupmod-simp-sssd
    stdlib: https://github.com/simp/puppetlabs-stdlib
    oath: https://github.com/simp/pupmod-simp-oath
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    pam: "#{source_dir}"

