---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd.git
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh.git
    authselect: https://github.com/voxpupuli/puppet-authselect.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    haveged: https://github.com/simp/pupmod-simp-haveged.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    logrotate: https://github.com/simp/pupmod-simp-logrotate.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    oddjob: https://github.com/simp/pupmod-simp-oddjob.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    ssh: https://github.com/simp/pupmod-simp-ssh.git
    sssd: https://github.com/simp/pupmod-simp-sssd.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
    oath: https://github.com/simp/pupmod-simp-oath.git
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers.git
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7.git
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
  symlinks:
    pam: "#{source_dir}"
