<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el6:
    roles:
      - default
      - master
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant

  el7:
    roles:
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: vagrant

CONFIG:
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
  log_level: verbose
  type: aio
