<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/$releasever/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc

  el6:
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/$releasever/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc

  el8:
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/$releasever/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc

CONFIG:
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
  log_level: verbose
  type: aio
